# Generated by Django 5.2 on 2025-04-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subcategories_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default=None, max_length=30, null=True),
        ),
    ]
