# Generated by Django 5.2 on 2025-05-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_subcategories_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PAID", "PAID"),
                    ("FAILED", "FAILED"),
                    ("REFUNDED", "REFUNDED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
