# Generated by Django 5.2 on 2025-05-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_orders_orderid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="receiptid",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
