# Generated by Django 5.2 on 2025-05-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_payments_receiptid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="orderid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="payments",
            name="receiptid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
